### ISSUE TITLE
How to communicate two viewModels?

### ISSUE THREAD

**Issue by sjahongir** [Catel/Catel.Examples#10]

**Comment by GeertvanHorrik** [comment]
There are different options:

1. Services (view models contain view-specific state, service contain app-state and are long-loving objects)
2. Messaging (we don't use this ourselves, but it's supported by Catel)

**Comment by sjahongir** [comment]
Can I use InterestedInAttribute to communicate two viewModels?

**Comment by GeertvanHorrik** [comment]
I think we removed that one from Catel 5 (or at least we don't recommend you using it). Services are better.

**Comment by sjahongir** [comment]
I see! 
But I can not find any sample about using viewmodel service, can you explain how I use or do you have example?

**Comment by GeertvanHorrik** [comment]
See https://github.com/WildGums/CsvTextEditor/blob/develop/src/CsvTextEditor/ViewModels/SettingsViewModel.cs

**Comment by sjahongir** [comment]
Thanks a lot!

**Comment by sjahongir** [comment]
I see SettingsViewModel.cs, but I can not understand fully. 

I have two viewmodels/view as QueryViewModel/QueryView and FilterViewModel/FilterView.
`public class QueryViewModel : ViewModelBase
    {
          public FiltersViewModel Filters { get; set; }
          ...
    }`

`public class FiltersViewModel : ViewModelBase
    {
         ...
    }`

How can I get filter values from FilterViewModel and set it to Filters property of QueryViewModel?

**Comment by GeertvanHorrik** [comment]
A view model should not contain another view model. You should only have models + services in a view model. Please check out the whole example.

**Comment by sjahongir** [comment]
Should it be so?

`public class FilterModel { ... }`
`public class QueryViewModel : ViewModelBase { public FilterModel Filter { get; set; } ... }`
`public class FiltersViewModel : ViewModelBase { ... }`
