### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by ttustonic** [Catel/Catel.Examples#53]
Hello
Do these examples work?
I just downloaded the zip file with the code, and when I try to build (Visual Studio 2017) I get more than 50 errors.

The error list is in the attachment
Thanks, Tom

[builderrors.txt](https://github.com/Catel/Catel.Examples/files/2730096/builderrors.txt)

**Comment by GeertvanHorrik** [comment]
Just pushed a fix that should make all WPF projects compilable again.

**Comment by ttustonic** [comment]
Hello, thanks
But, no, it still doesn't build. There are no references to wpf dlls (windowsbase, presentationframework, etc.). When I add these references, I have to explicitly set inheritance (for example, in App.xaml.cs I have to set that it inherits from Application, similar to views and Datawindow). 
After that, I get the errors 
> The name 'InitializeComponent' does not exist in the current context

because g.i.cs files are not generated. Also, I get the error 
> Program does not contain a static 'Main' method suitable for an entry point

Cheers,
Tom

**Comment by GeertvanHorrik** [comment]
Checking into this again. It works fine in a prerelease version of VS. Checking stable VS versions now.

**Comment by GeertvanHorrik** [comment]
Yep, fails in stable. Will revert the MSBuild Sdk Extras changes.

**Comment by GeertvanHorrik** [comment]
Fixed, thanks for reporting!
