### ISSUE TITLE
Examples Projects not compiling

### ISSUE THREAD

**Issue by bigworld12** [Catel/Catel.Examples#70]
### Steps to reproduce

1. Clone solution as is
2. Build any wpf project
3. Build fails

i think this is due to wrong project files, current ones are using `Microsoft.NET.Sdk` when it should be `Microsoft.NET.Sdk.WindowsDesktop` also looks like the project is using old build targets

Platform:
.NET version: 
.net framework 4.7.2
.net core: 3.0.100-preview-010184

**Comment by GeertvanHorrik** [comment]
All WPF projects should succeed now.
